### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by lucinauddin** [Brainhack-Proceedings-2015/Frohlich-AMX-BrainMusic#2]
Interesting work! One suggestion: it would be helpful to the reviewers to give some background in the intro about where this idea originated. A minor point is to spell out terms (eg. MIDI) the first time they are used.

**Comment by carolFrohlich** [comment]
Tried to accommodate the modifications without writing more than the allowed number of words.
Thanks  for the review!

**Comment by nicholsn** [comment]
@carolFrohlich have you had a chance to commit these modifications? I don't see any additional commits or PR to the repo. Thanks!

**Comment by ccraddock** [comment]
@nicholsn I just merged the pull request, sorry that I didn't notice it before. Would you please check if the changes are sufficient? 

-cc
